# Generated by Django 4.0.6 on 2022-07-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
