# Generated by Django 4.0.6 on 2022-07-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_featured_image_post_featured_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
