# Generated by Django 4.0.6 on 2022-07-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_date_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
