# Generated by Django 4.0.6 on 2022-07-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_reply_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='status',
            new_name='is_accepted',
        ),
    ]
